// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RobotManagmentApi.context;

namespace RobotManagmentApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230718090031_FirstMigs")]
    partial class FirstMigs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RobotManagmentApi.Models.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Robots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirmwareVersion = "22PQ3T",
                            ImagePath = "robot.jpg",
                            Location = "Junagadh",
                            OwnerName = "akshay",
                            RobotFeatures = "A versatile robot designed to assist in various tasks with its advanced AI, including cleaning, cooking, and personal assistance.",
                            RobotName = "RoboMax"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirmwareVersion = "23SOq4",
                            ImagePath = "robot6.jpg",
                            Location = "Suart",
                            OwnerName = "Omdev",
                            RobotFeatures = "An innovative robot equipped with cutting-edge technology, capable of autonomous navigation and data analysis for research and surveillance",
                            RobotName = "CyberBot"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirmwareVersion = "23SOW4",
                            ImagePath = "robot2.jpg",
                            Location = "Junagadh",
                            OwnerName = "Akshay",
                            RobotFeatures = "A rugged and agile robot designed for planetary exploration, equipped with high-resolution cameras and sample collection tools.",
                            RobotName = "MechWarrior"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirmwareVersion = "23SOD4",
                            ImagePath = "robot3.jpg",
                            Location = "Suart",
                            OwnerName = "Omdev",
                            RobotFeatures = "A nimble flying robot with exceptional maneuverability, ideal for aerial photography and surveillance missions",
                            RobotName = "TitanTron"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirmwareVersion = "23S5V4",
                            ImagePath = "robot4.jpg",
                            Location = "Junagadh",
                            OwnerName = "Akshay",
                            RobotFeatures = "A medical robot with AI-driven diagnostics, capable of assisting in surgeries and patient care in hospitals.",
                            RobotName = "GalaxyBots"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirmwareVersion = "23S6X4",
                            ImagePath = "robot5.jpg",
                            Location = "Suart",
                            OwnerName = "Omdev",
                            RobotFeatures = "An agricultural robot designed to automate farming tasks, including planting, watering, and harvesting crops.",
                            RobotName = "NanoDroid"
                        });
                });

            modelBuilder.Entity("RobotManagmentApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ResetPasswordExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
